Names=['Sadaf','Aliya','Ammara','Angel','Liya','Shaima','Asfia','Dania','Aisha','Zeenat']
print('Hello',Names [0],'How have you been ?')
print('Hello',Names [1],'How have you been ?')
print('Hello',Names [2],'How have you been ?')
print('Hello',Names [3],'How have you been ?')
print('Hello',Names [4],'How have you been ?')
print('Hello',Names [5],'How have you been ?')
print('Hello',Names [6],'How have you been ?')
print('Hello',Names [7],'How have you been ?')
print('Hello',Names [8],'How have you been ?')
print('Hello',Names [9],'How have you been ?')